version: '2'

services:
  zookeeper1:
    build:
      dockerfile: Dockerfile.zookeeper
      context: .
      args:
        myid: 1
    networks:
      - back
    ports:
      - "21811:2181"
      - "28881:2888"
      - "38881:3888"
  zookeeper2:
    build:
      dockerfile: Dockerfile.zookeeper
      context: .
      args:
        myid: 2
    networks:
      - back
    ports:
      - "21812:2181"
      - "28882:2888"
      - "38882:3888"
  zookeeper3:
    build:
      dockerfile: Dockerfile.zookeeper
      context: .
      args:
        myid: 3
    networks:
      - back
    ports:
      - "21813:2181"
      - "28883:2888"
      - "38883:3888"

  zkcli:
    build:
      dockerfile: Dockerfile.zkcli
      context: .
    stdin_open: true
    tty: true
    networks:
      - back

networks:
  back:
    driver: bridge
